### ISSUE TITLE
Installation for pecan-style fails

### ISSUE THREAD

**Issue by inftp** [zzzeyez/pecan#10]
When trying to configure and install pecan-style, the following command fails:

`sed -i -e "s~/Users/zzzeyez/scripts/uber~HOME/Library/Application\ Support/Übersicht/widgets~g" "$HOME/Library/Application\ Support/Übersicht/widgets/Pecan/pecan-style"`

And returns:

`sed: /Users/inftp/Library/Application\ Support/Übersicht/widgets/Pecan/pecan-style: No such file or directory`

This is using Übersicht's default settings and cloning Pecan into "~/Library/Application Support/Übersicht/widgets"

**Comment by theodugautier** [comment]
+1 same problem

**Comment by nythepegasus** [comment]
@inftp @theodugautier Get rid of the quotes on the second thing. It's escaping a " " (space) in quotes, which is a big no no in bash.

**Comment by Elevate08** [comment]
I've moved all of my plugins to a scripts folder inside my home directory.

ex. /Users/elevate/scripts/uber/widgets/

Then I was able to modify the paths in the appropriate files "pecan-style", "wal-set", style.scss, anything else I may have forgotten about.

I believe part of the issue is the Ü not being read correctly.

**Comment by zzzeyez** [comment]
the Ü character does indeed cause lots of issues!  but i have changed everything to user Übersicht's default location and this should alleviate all these problems.  but in response to the first post:  yes escaping that space was the issue
